
[pytest]
env =
    NODE_TLS_REJECT_UNAUTHORIZED=0
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s

pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --html=reports/report.html
    --self-contained-html
    -ra
    --strict-markers
    --screenshot only-on-failure

markers =
    smoke: smoke tests
    regression: regression tests
    slow: slow tests
