[pytest]
pythonpath = .
testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v --headed
    -ra
    --strict-markers

markers =
    smoke: smoke tests
    regression: regression tests
    slow: slow tests
